-- MySQL Script generated by MySQL Workbench
-- Sun Jan 30 20:02:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PA_Pharmacy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PA_Pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PA_Pharmacy` DEFAULT CHARACTER SET utf8 ;
USE `PA_Pharmacy` ;

-- -----------------------------------------------------
-- Table `PA_Pharmacy`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PA_Pharmacy`.`Doctor` (
  `DoctorID` INT NOT NULL AUTO_INCREMENT,
  `SSN` VARCHAR(45) NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `Specialty` VARCHAR(45) NOT NULL,
  `StartPractice` DATE NOT NULL,
  PRIMARY KEY (`DoctorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PA_Pharmacy`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PA_Pharmacy`.`Patient` (
  `PatientID` INT NOT NULL AUTO_INCREMENT,
  `SSN` VARCHAR(45) NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Doctor_DoctorID` INT NOT NULL,
  PRIMARY KEY (`PatientID`),
  INDEX `fk_Patient_Doctor1_idx` (`Doctor_DoctorID` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_Doctor1`
    FOREIGN KEY (`Doctor_DoctorID`)
    REFERENCES `PA_Pharmacy`.`Doctor` (`DoctorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PA_Pharmacy`.`Drug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PA_Pharmacy`.`Drug` (
  `DrugID` INT NOT NULL,
  `TradeName` VARCHAR(45) NOT NULL,
  `GenericName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DrugID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PA_Pharmacy`.`RX`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PA_Pharmacy`.`RX` (
  `RxID` INT NOT NULL,
  `_DrugID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `DateIssued` DATE NOT NULL,
  `DateFilled` DATE NULL,
  `Doctor_DoctorID` INT NOT NULL,
  `Patient_PatientID` INT NOT NULL,
  PRIMARY KEY (`RxID`),
  INDEX `fk_RX_Drug1_idx` (`_DrugID` ASC) VISIBLE,
  INDEX `fk_RX_Doctor1_idx` (`Doctor_DoctorID` ASC) VISIBLE,
  INDEX `fk_RX_Patient1_idx` (`Patient_PatientID` ASC) VISIBLE,
  CONSTRAINT `fk_RX_Drug1`
    FOREIGN KEY (`_DrugID`)
    REFERENCES `PA_Pharmacy`.`Drug` (`DrugID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RX_Doctor1`
    FOREIGN KEY (`Doctor_DoctorID`)
    REFERENCES `PA_Pharmacy`.`Doctor` (`DoctorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RX_Patient1`
    FOREIGN KEY (`Patient_PatientID`)
    REFERENCES `PA_Pharmacy`.`Patient` (`PatientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PA_Pharmacy`.`Pharmacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PA_Pharmacy`.`Pharmacy` (
  `PharmacyID` INT NOT NULL AUTO_INCREMENT,
  `PharmacyName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `PhoneNum` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PharmacyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PA_Pharmacy`.`DrugPrice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PA_Pharmacy`.`DrugPrice` (
  `PriceID` INT NOT NULL AUTO_INCREMENT,
  `_DrugID` INT NOT NULL,
  `_PharmacyID` INT NOT NULL,
  `Price` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`PriceID`),
  INDEX `fk_DrugPrice_Pharmacy1_idx` (`_PharmacyID` ASC) VISIBLE,
  INDEX `fk_DrugPrice_Drug1_idx` (`_DrugID` ASC) VISIBLE,
  CONSTRAINT `fk_DrugPrice_Pharmacy1`
    FOREIGN KEY (`_PharmacyID`)
    REFERENCES `PA_Pharmacy`.`Pharmacy` (`PharmacyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DrugPrice_Drug1`
    FOREIGN KEY (`_DrugID`)
    REFERENCES `PA_Pharmacy`.`Drug` (`DrugID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PA_Pharmacy`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PA_Pharmacy`.`Supplier` (
  `SupplierID` INT NOT NULL AUTO_INCREMENT,
  `SupplierName` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PA_Pharmacy`.`Supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PA_Pharmacy`.`Supervisor` (
  `SupervisorID` INT NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SupervisorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PA_Pharmacy`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PA_Pharmacy`.`Contract` (
  `ContractID` INT NOT NULL AUTO_INCREMENT,
  `_SupervisorID` INT NOT NULL,
  `_PharmacyID` INT NOT NULL,
  `_SupplierID` INT NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `ContractTerms` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`ContractID`, `_PharmacyID`, `_SupplierID`),
  INDEX `fk_Contract_Pharmacy1_idx` (`_PharmacyID` ASC) VISIBLE,
  INDEX `fk_Contract_Supplier1_idx` (`_SupplierID` ASC) VISIBLE,
  INDEX `fk_Contract_Supervisor1_idx` (`_SupervisorID` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Pharmacy1`
    FOREIGN KEY (`_PharmacyID`)
    REFERENCES `PA_Pharmacy`.`Pharmacy` (`PharmacyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_Supplier1`
    FOREIGN KEY (`_SupplierID`)
    REFERENCES `PA_Pharmacy`.`Supplier` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_Supervisor1`
    FOREIGN KEY (`_SupervisorID`)
    REFERENCES `PA_Pharmacy`.`Supervisor` (`SupervisorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

alter table doctor
rename column Fname TO name;

alter table doctor
drop column Lname;

alter table doctor
rename column StartPractice To practice_since;

alter table doctor modify practice_since INTEGER;

alter table doctor
rename column DoctorID To id;